theme: jekyll-theme-minimal
title: Pharmaceutical Engineering
description: The records of what I have learned about pharmaceutical engineering, including how to design pharmaceutical skids and warehoures, new technologies and uptodate news.
